name: Generate GitHub Pages Example

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install and build
        run: |
          npm ci
          npm run build

  publish-gh-pages:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: actions/checkout@v1
        run: |
          ls -laF
          git branch -v
