name: Generate GitHub Pages Example

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: npm install and build
        run: |
          npm ci
          npm run build

      - name: Deploy
        run: |
          ls -laF
          echo printenv
